import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth/tenant";

export default async function CommandCenter({ searchParams }: { searchParams: Promise<{ business?: string }> }) {
  const { supabase } = await requireUser();
  const params = await searchParams;
  const { data: businesses } = await supabase.from("businesses").select("id,name,ai_active,auto_send_active,autonomy_level").order("created_at");
  if (!businesses?.length) redirect("/setup");
  const businessId = params.business && businesses.some((b) => b.id === params.business) ? params.business : businesses[0].id;
  const business = businesses.find((b) => b.id === businessId)!;
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const [messages, runs, approvals, threads, mailboxes] = await Promise.all([
    supabase.from("email_messages").select("id", { count: "exact", head: true }).eq("business_id", businessId).gte("created_at", since),
    supabase.from("agent_runs").select("id,status", { count: "exact" }).eq("business_id", businessId).gte("created_at", since),
    supabase.from("approvals").select("id,agent_run_id,risk,proposed_draft,created_at,agent_runs!inner(email_messages!inner(from_address,subject))").eq("business_id", businessId).eq("status", "PENDING").order("created_at", { ascending: false }).limit(20),
    supabase.from("email_threads").select("id,subject,status,risk,last_activity_at,mailboxes!inner(email_address),contacts(email,first_name,last_name)").eq("business_id", businessId).order("last_activity_at", { ascending: false }).limit(30),
    supabase.from("mailboxes").select("id,email_address,provider,ai_active,auto_send_active,watch_expires_at").eq("business_id", businessId),
  ]);
  const runRows = runs.data ?? [];
  const aiHandled = runRows.filter((r: any) => ["COMPLETED","AWAITING_APPROVAL","DECIDED"].includes(r.status)).length;
  return <main className="shell"><div className="topbar"><div><h1 style={{margin:0}}>AI Agent Email OS</h1><div className="muted">{business.name} · autonomy {business.autonomy_level} · AI {business.ai_active ? "on" : "off"} · auto-send {business.auto_send_active ? "on" : "off"}</div></div><div className="actions"><a className="btn" href={`/settings?business=${businessId}`}>Settings</a><a className="btn" href={`/api/integrations/gmail/connect?businessId=${businessId}`}>Connect Gmail</a><a className="btn" href={`/api/integrations/ghl/connect?businessId=${businessId}`}>Connect GHL</a></div></div><section className="grid"><div className="card"><div className="muted">Messages today</div><div className="metric">{messages.count ?? 0}</div></div><div className="card"><div className="muted">AI runs today</div><div className="metric">{runs.count ?? 0}</div></div><div className="card"><div className="muted">AI handled</div><div className="metric">{aiHandled}</div></div><div className="card"><div className="muted">Pending approvals</div><div className="metric">{approvals.data?.length ?? 0}</div></div></section><section className="section"><h2>Mailboxes</h2><div className="grid">{(mailboxes.data ?? []).map((m: any) => <div className="card" key={m.id}><strong>{m.email_address}</strong><div className="muted">{m.provider} · AI {m.ai_active ? "on" : "off"} · auto {m.auto_send_active ? "on" : "off"}</div></div>)}</div></section><section className="section"><h2>Approval queue</h2><table className="table"><thead><tr><th>From</th><th>Subject</th><th>Risk</th><th>Draft</th><th>Action</th></tr></thead><tbody>{(approvals.data ?? []).map((a: any) => { const msg = a.agent_runs?.email_messages; return <tr key={a.id}><td>{msg?.from_address ?? ""}</td><td>{msg?.subject ?? ""}</td><td><span className="badge">{a.risk}</span></td><td>{String(a.proposed_draft?.bodyText ?? "").slice(0,240)}</td><td><div className="actions"><form action={`/api/approvals/${a.id}/approve`} method="post"><button className="btn primary">Approve & Send</button></form><form action={`/api/approvals/${a.id}/reject`} method="post"><button className="btn">Reject</button></form></div></td></tr>; })}</tbody></table></section><section className="section"><h2>Unified inbox</h2><table className="table"><thead><tr><th>Mailbox</th><th>Contact</th><th>Subject</th><th>Risk</th><th>Status</th><th>Last activity</th></tr></thead><tbody>{(threads.data ?? []).map((t: any) => <tr key={t.id}><td>{t.mailboxes?.email_address}</td><td>{t.contacts ? `${t.contacts.first_name ?? ""} ${t.contacts.last_name ?? ""}`.trim() || t.contacts.email : "Unmatched"}</td><td>{t.subject}</td><td>{t.risk ?? "-"}</td><td>{t.status}</td><td>{new Date(t.last_activity_at).toLocaleString()}</td></tr>)}</tbody></table></section></main>;
}
